                        name: Deploy to Google Cloud

                        on:
                          push:
                            branches:
                              - main  # Trigger deployment on push to the main branch

                        jobs:
                          deploy:
                            runs-on: ubuntu-latest

                            steps:
                            - name: Checkout repository
                              uses: actions/checkout@v2

                            - name: Set up Google Cloud SDK
                              uses: google-github-actions/setup-gcloud@v0.2.0
                              with:
                                version: 'latest'
                                project_id: ${{ secrets.PROJECT_ID }}
                                service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}

                            - name: Ensure SSH key exists
                              run: |
                                mkdir -p ~/.ssh
                                if [ ! -f ~/.ssh/google_compute_engine ]; then
                                  ssh-keygen -t rsa -f ~/.ssh/google_compute_engine -C "${{ secrets.GITHUB_ACTOR }}" -N ""
                                fi
                                # Add SSH key for Google Cloud
                                gcloud compute os-login ssh-keys add --key-file=~/.ssh/google_compute_engine.pub --project ${{ secrets.PROJECT_ID }}

                            - name: Add SSH key to SSH agent
                              run: |
                                eval "$(ssh-agent -s)"
                                ssh-add ~/.ssh/google_compute_engine

                            - name: Deploy to Google Compute Engine
                              run: |
                                gcloud compute ssh trouys16@${{ secrets.INSTANCE_NAME }} \
                                  --project ${{ secrets.PROJECT_ID }} \
                                  --zone ${{ secrets.ZONE }} \
                                  --command "cd /home/trouys16/Jobby && ./deploy.sh"